name: converternow
version: 3.2.1
title: Unit Converter
summary: Unit and currencies converter
description: A Unit and Currencies Converter. Converter NOW is immediate, fast and easy to use!

confinement: strict
base: core18
grade: stable

architectures:
  - build-on: amd64
    run-on: [amd64, i386, arm64]

slots:
  dbus-converternow:
    interface: dbus
    bus: session
    name: com.ferrarid.converternow
    
apps:
  converternow:
    command: converternow
    extensions: [flutter-stable]
    plugs:
    - network
    slots:
      - dbus-converternow
parts:
  converternow:
    override-build: |
      dart pub global activate melos
      export PATH="$PATH":"$HOME/.pub-cache/bin"
      melos bootstrap
      snapcraftctl build
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
